(* Three-lane matrix sorter with nine trailer doors.
   Generated by gen_sorter.py. Do not hand edit; regenerate instead. *)

TYPE
  BELT_T : ARRAY[0..19] OF INT;
END_TYPE

PROGRAM sorter
VAR
  sorter_run    AT %QX110.0    : BOOL;   (* operator master run *)
  auto_mode     AT %QX110.1    : BOOL;   (* auto routing enabled *)
  lane1_run     AT %QX110.2    : BOOL;   (* induct 1 running *)
  lane2_run     AT %QX110.3    : BOOL;   (* induct 2 running *)
  lane3_run     AT %QX110.4    : BOOL;   (* induct 3 running *)
  ob1_run       AT %QX110.5    : BOOL;   (* outbound 1 running *)
  ob2_run       AT %QX110.6    : BOOL;   (* outbound 2 running *)
  ob3_run       AT %QX110.7    : BOOL;   (* outbound 3 running *)
  l1_div1       AT %QX111.0    : BOOL;   (* lane 1 divert to outbound 1 *)
  l1_div2       AT %QX111.1    : BOOL;   (* lane 1 divert to outbound 2 *)
  l1_div3       AT %QX111.2    : BOOL;   (* lane 1 divert to outbound 3 *)
  l2_div1       AT %QX111.3    : BOOL;   (* lane 2 divert to outbound 1 *)
  l2_div2       AT %QX111.4    : BOOL;   (* lane 2 divert to outbound 2 *)
  l2_div3       AT %QX111.5    : BOOL;   (* lane 2 divert to outbound 3 *)
  l3_div1       AT %QX111.6    : BOOL;   (* lane 3 divert to outbound 1 *)
  l3_div2       AT %QX111.7    : BOOL;   (* lane 3 divert to outbound 2 *)
  l3_div3       AT %QX112.0    : BOOL;   (* lane 3 divert to outbound 3 *)
  b1_door1      AT %QX112.1    : BOOL;   (* outbound 1 divert to door 1 *)
  b1_door2      AT %QX112.2    : BOOL;   (* outbound 1 divert to door 2 *)
  b1_door3      AT %QX112.3    : BOOL;   (* outbound 1 divert to door 3 *)
  b2_door1      AT %QX112.4    : BOOL;   (* outbound 2 divert to door 1 *)
  b2_door2      AT %QX112.5    : BOOL;   (* outbound 2 divert to door 2 *)
  b2_door3      AT %QX112.6    : BOOL;   (* outbound 2 divert to door 3 *)
  b3_door1      AT %QX112.7    : BOOL;   (* outbound 3 divert to door 1 *)
  b3_door2      AT %QX113.0    : BOOL;   (* outbound 3 divert to door 2 *)
  b3_door3      AT %QX113.1    : BOOL;   (* outbound 3 divert to door 3 *)
  jam_alarm     AT %QX113.2    : BOOL;   (* induct belt backing up at the tail *)
  coll_alarm    AT %QX113.3    : BOOL;   (* merge collision on an outbound belt *)
  noread_alarm  AT %QX113.4    : BOOL;   (* tunnel no-read *)
  nohome_alarm  AT %QX113.5    : BOOL;   (* package reached end of an outbound belt *)
  reset_cmd     AT %QX113.6    : BOOL;   (* re-run the init block, clearing all process state *)
  fault_reset   AT %QX113.7    : BOOL;   (* hold the drive fault-reset bit for several scans *)
  scanner_fault_ack AT %QX114.0 : BOOL; (* operator acknowledges scanner fault *)
  scanner_retry AT %QX114.1 : BOOL;     (* operator retries after acknowledgement *)
  xle_mode AT %QX114.2 : BOOL;           (* lane 1 external sort decisions *)

  speed_sp_1    AT %QW200      : INT;    (* induct 1 speed setpoint, rpm *)
  speed_sp_2    AT %QW201      : INT;    (* induct 2 speed setpoint, rpm *)
  speed_sp_3    AT %QW202      : INT;    (* induct 3 speed setpoint, rpm *)
  ob_speed_1    AT %QW203      : INT;    (* outbound 1 speed setpoint, rpm *)
  ob_speed_2    AT %QW204      : INT;    (* outbound 2 speed setpoint, rpm *)
  ob_speed_3    AT %QW205      : INT;    (* outbound 3 speed setpoint, rpm *)
  min_gap_sp    AT %QW206      : INT;    (* minimum induct gap, cells *)
  rate_sp_1     AT %QW207      : INT;    (* induct 1 interval, scans per package *)
  rate_sp_2     AT %QW208      : INT;    (* induct 2 interval, scans per package *)
  rate_sp_3     AT %QW209      : INT;    (* induct 3 interval, scans per package *)
  noread_sp     AT %QW210      : INT;    (* tunnel no-read rate, per mille *)
  scan_code_1   AT %QW211      : INT;    (* last barcode read by tunnel 1 *)
  scan_code_2   AT %QW212      : INT;    (* last barcode read by tunnel 2 *)
  scan_code_3   AT %QW213      : INT;    (* last barcode read by tunnel 3 *)
  noread_ct     AT %QW214      : INT;    (* cumulative tunnel no-reads *)
  coll_ct       AT %QW215      : INT;    (* cumulative merge collisions *)
  jam_ct        AT %QW216      : INT;    (* cumulative induct belt jams *)
  missort_ct    AT %QW217      : INT;    (* cumulative confirmed missorts at door scan *)
  recirc_ct     AT %QW218      : INT;    (* packages undiverted off an induct belt *)
  nohome_ct     AT %QW219      : INT;    (* packages undiverted off an outbound belt *)
  inducted_ct   AT %QW220      : INT;    (* cumulative packages inducted *)
  serial_next   AT %QW221      : INT;    (* next package serial number *)
  tr11_ct       AT %QW222      : INT;    (* packages loaded to trailer 1-1 *)
  tr12_ct       AT %QW223      : INT;    (* packages loaded to trailer 1-2 *)
  tr13_ct       AT %QW224      : INT;    (* packages loaded to trailer 1-3 *)
  tr21_ct       AT %QW225      : INT;    (* packages loaded to trailer 2-1 *)
  tr22_ct       AT %QW226      : INT;    (* packages loaded to trailer 2-2 *)
  tr23_ct       AT %QW227      : INT;    (* packages loaded to trailer 2-3 *)
  tr31_ct       AT %QW228      : INT;    (* packages loaded to trailer 3-1 *)
  tr32_ct       AT %QW229      : INT;    (* packages loaded to trailer 3-2 *)
  tr33_ct       AT %QW230      : INT;    (* packages loaded to trailer 3-3 *)
  tr11_bad      AT %QW231      : INT;    (* wrong-destination loads at trailer 1-1 *)
  tr12_bad      AT %QW232      : INT;    (* wrong-destination loads at trailer 1-2 *)
  tr13_bad      AT %QW233      : INT;    (* wrong-destination loads at trailer 1-3 *)
  tr21_bad      AT %QW234      : INT;    (* wrong-destination loads at trailer 2-1 *)
  tr22_bad      AT %QW235      : INT;    (* wrong-destination loads at trailer 2-2 *)
  tr23_bad      AT %QW236      : INT;    (* wrong-destination loads at trailer 2-3 *)
  tr31_bad      AT %QW237      : INT;    (* wrong-destination loads at trailer 3-1 *)
  tr32_bad      AT %QW238      : INT;    (* wrong-destination loads at trailer 3-2 *)
  tr33_bad      AT %QW239      : INT;    (* wrong-destination loads at trailer 3-3 *)
  div_act_1     AT %QW240      : INT;    (* outbound 1 induct-divert actuations *)
  div_act_2     AT %QW241      : INT;    (* outbound 2 induct-divert actuations *)
  div_act_3     AT %QW242      : INT;    (* outbound 3 induct-divert actuations *)
  scan_ct       AT %QW243      : INT;    (* PLC scans since init, logical clock *)
  shift_ct_1    AT %QW244      : INT;    (* induct 1 belt shifts since init *)
  shift_ct_2    AT %QW245      : INT;    (* induct 2 belt shifts since init *)
  shift_ct_3    AT %QW246      : INT;    (* induct 3 belt shifts since init *)
  master_seed   AT %QW247      : INT;    (* PRNG root, 1..999, 0 means use default *)
  run_id        AT %QW248      : INT;    (* scenario run identifier, echoed into telemetry *)
  prog_hash     AT %QW249      : INT;    (* identity of the generated program, set at init *)
  multiple_ct   AT %QW250      : INT;    (* tunnel reported more than one barcode *)
  oversize_ct   AT %QW251      : INT;    (* package exceeded the tunnel size limit *)
  duplicate_ct  AT %QW252      : INT;    (* tunnel returned a barcode already seen *)
  invalid_ct    AT %QW253      : INT;    (* tunnel decoded something that is not a label *)
  scan_late_ct  AT %QW254      : INT;    (* package left the tunnel before its result arrived *)
  scanner_state AT %QW255 : INT;        (* 0 ready, 1 prepare, 2 reset, 3 fault, 4 acknowledged *)
  scanner_fault_mask AT %QW256 : INT;   (* bits 0,1,2 identify missing tunnel ACKs *)
  scanner_ack_mask AT %QW257 : INT;     (* bits 0,1,2 for current phase ACKs *)
  scanner_wait AT %QW258 : INT;         (* elapsed PLC scans in current phase *)
  xle_cmd_id AT %QW500 : INT;            (* XLe writes 500..503 *)
  xle_cmd_bc AT %QW501 : INT;
  xle_cmd_dest AT %QW502 : INT;
  xle_cmd_nonce AT %QW503 : INT;
  xle_ack_id AT %QW504 : INT;            (* PLC writes 504..509 *)
  xle_state AT %QW505 : INT;             (* 0 idle, 1 accepted, 2 diverted, 3 loaded, 4 failed, 5 recirc *)
  xle_reason AT %QW506 : INT;            (* 1 no decision, 2 invalid/late, 3 collision, 4 no home, 5 wrong door *)
  xle_actual AT %QW507 : INT;            (* physical trailer, 1..9 *)
  xle_package AT %QW508 : INT;           (* scanner barcode identity *)
  xle_run_nonce AT %QW509 : INT;

  ib1_c0          AT %QW260      : INT;
  ib1_c1          AT %QW261      : INT;
  ib1_c2          AT %QW262      : INT;
  ib1_c3          AT %QW263      : INT;
  ib1_c4          AT %QW264      : INT;
  ib1_c5          AT %QW265      : INT;
  ib1_c6          AT %QW266      : INT;
  ib1_c7          AT %QW267      : INT;
  ib1_c8          AT %QW268      : INT;
  ib1_c9          AT %QW269      : INT;
  ib1_c10         AT %QW270      : INT;
  ib1_c11         AT %QW271      : INT;
  ib1_c12         AT %QW272      : INT;
  ib1_c13         AT %QW273      : INT;
  ib1_c14         AT %QW274      : INT;
  ib1_c15         AT %QW275      : INT;
  ib1_c16         AT %QW276      : INT;
  ib1_c17         AT %QW277      : INT;
  ib1_c18         AT %QW278      : INT;
  ib1_c19         AT %QW279      : INT;
  ib2_c0          AT %QW280      : INT;
  ib2_c1          AT %QW281      : INT;
  ib2_c2          AT %QW282      : INT;
  ib2_c3          AT %QW283      : INT;
  ib2_c4          AT %QW284      : INT;
  ib2_c5          AT %QW285      : INT;
  ib2_c6          AT %QW286      : INT;
  ib2_c7          AT %QW287      : INT;
  ib2_c8          AT %QW288      : INT;
  ib2_c9          AT %QW289      : INT;
  ib2_c10         AT %QW290      : INT;
  ib2_c11         AT %QW291      : INT;
  ib2_c12         AT %QW292      : INT;
  ib2_c13         AT %QW293      : INT;
  ib2_c14         AT %QW294      : INT;
  ib2_c15         AT %QW295      : INT;
  ib2_c16         AT %QW296      : INT;
  ib2_c17         AT %QW297      : INT;
  ib2_c18         AT %QW298      : INT;
  ib2_c19         AT %QW299      : INT;
  ib3_c0          AT %QW300      : INT;
  ib3_c1          AT %QW301      : INT;
  ib3_c2          AT %QW302      : INT;
  ib3_c3          AT %QW303      : INT;
  ib3_c4          AT %QW304      : INT;
  ib3_c5          AT %QW305      : INT;
  ib3_c6          AT %QW306      : INT;
  ib3_c7          AT %QW307      : INT;
  ib3_c8          AT %QW308      : INT;
  ib3_c9          AT %QW309      : INT;
  ib3_c10         AT %QW310      : INT;
  ib3_c11         AT %QW311      : INT;
  ib3_c12         AT %QW312      : INT;
  ib3_c13         AT %QW313      : INT;
  ib3_c14         AT %QW314      : INT;
  ib3_c15         AT %QW315      : INT;
  ib3_c16         AT %QW316      : INT;
  ib3_c17         AT %QW317      : INT;
  ib3_c18         AT %QW318      : INT;
  ib3_c19         AT %QW319      : INT;

  rt1_c0          AT %QW320      : INT;
  rt1_c1          AT %QW321      : INT;
  rt1_c2          AT %QW322      : INT;
  rt1_c3          AT %QW323      : INT;
  rt1_c4          AT %QW324      : INT;
  rt1_c5          AT %QW325      : INT;
  rt1_c6          AT %QW326      : INT;
  rt1_c7          AT %QW327      : INT;
  rt1_c8          AT %QW328      : INT;
  rt1_c9          AT %QW329      : INT;
  rt1_c10         AT %QW330      : INT;
  rt1_c11         AT %QW331      : INT;
  rt1_c12         AT %QW332      : INT;
  rt1_c13         AT %QW333      : INT;
  rt1_c14         AT %QW334      : INT;
  rt1_c15         AT %QW335      : INT;
  rt1_c16         AT %QW336      : INT;
  rt1_c17         AT %QW337      : INT;
  rt1_c18         AT %QW338      : INT;
  rt1_c19         AT %QW339      : INT;
  rt2_c0          AT %QW340      : INT;
  rt2_c1          AT %QW341      : INT;
  rt2_c2          AT %QW342      : INT;
  rt2_c3          AT %QW343      : INT;
  rt2_c4          AT %QW344      : INT;
  rt2_c5          AT %QW345      : INT;
  rt2_c6          AT %QW346      : INT;
  rt2_c7          AT %QW347      : INT;
  rt2_c8          AT %QW348      : INT;
  rt2_c9          AT %QW349      : INT;
  rt2_c10         AT %QW350      : INT;
  rt2_c11         AT %QW351      : INT;
  rt2_c12         AT %QW352      : INT;
  rt2_c13         AT %QW353      : INT;
  rt2_c14         AT %QW354      : INT;
  rt2_c15         AT %QW355      : INT;
  rt2_c16         AT %QW356      : INT;
  rt2_c17         AT %QW357      : INT;
  rt2_c18         AT %QW358      : INT;
  rt2_c19         AT %QW359      : INT;
  rt3_c0          AT %QW360      : INT;
  rt3_c1          AT %QW361      : INT;
  rt3_c2          AT %QW362      : INT;
  rt3_c3          AT %QW363      : INT;
  rt3_c4          AT %QW364      : INT;
  rt3_c5          AT %QW365      : INT;
  rt3_c6          AT %QW366      : INT;
  rt3_c7          AT %QW367      : INT;
  rt3_c8          AT %QW368      : INT;
  rt3_c9          AT %QW369      : INT;
  rt3_c10         AT %QW370      : INT;
  rt3_c11         AT %QW371      : INT;
  rt3_c12         AT %QW372      : INT;
  rt3_c13         AT %QW373      : INT;
  rt3_c14         AT %QW374      : INT;
  rt3_c15         AT %QW375      : INT;
  rt3_c16         AT %QW376      : INT;
  rt3_c17         AT %QW377      : INT;
  rt3_c18         AT %QW378      : INT;
  rt3_c19         AT %QW379      : INT;

  ob1_c0          AT %QW380      : INT;
  ob1_c1          AT %QW381      : INT;
  ob1_c2          AT %QW382      : INT;
  ob1_c3          AT %QW383      : INT;
  ob1_c4          AT %QW384      : INT;
  ob1_c5          AT %QW385      : INT;
  ob1_c6          AT %QW386      : INT;
  ob1_c7          AT %QW387      : INT;
  ob1_c8          AT %QW388      : INT;
  ob1_c9          AT %QW389      : INT;
  ob1_c10         AT %QW390      : INT;
  ob1_c11         AT %QW391      : INT;
  ob1_c12         AT %QW392      : INT;
  ob1_c13         AT %QW393      : INT;
  ob1_c14         AT %QW394      : INT;
  ob1_c15         AT %QW395      : INT;
  ob1_c16         AT %QW396      : INT;
  ob1_c17         AT %QW397      : INT;
  ob1_c18         AT %QW398      : INT;
  ob1_c19         AT %QW399      : INT;
  ob2_c0          AT %QW400      : INT;
  ob2_c1          AT %QW401      : INT;
  ob2_c2          AT %QW402      : INT;
  ob2_c3          AT %QW403      : INT;
  ob2_c4          AT %QW404      : INT;
  ob2_c5          AT %QW405      : INT;
  ob2_c6          AT %QW406      : INT;
  ob2_c7          AT %QW407      : INT;
  ob2_c8          AT %QW408      : INT;
  ob2_c9          AT %QW409      : INT;
  ob2_c10         AT %QW410      : INT;
  ob2_c11         AT %QW411      : INT;
  ob2_c12         AT %QW412      : INT;
  ob2_c13         AT %QW413      : INT;
  ob2_c14         AT %QW414      : INT;
  ob2_c15         AT %QW415      : INT;
  ob2_c16         AT %QW416      : INT;
  ob2_c17         AT %QW417      : INT;
  ob2_c18         AT %QW418      : INT;
  ob2_c19         AT %QW419      : INT;
  ob3_c0          AT %QW420      : INT;
  ob3_c1          AT %QW421      : INT;
  ob3_c2          AT %QW422      : INT;
  ob3_c3          AT %QW423      : INT;
  ob3_c4          AT %QW424      : INT;
  ob3_c5          AT %QW425      : INT;
  ob3_c6          AT %QW426      : INT;
  ob3_c7          AT %QW427      : INT;
  ob3_c8          AT %QW428      : INT;
  ob3_c9          AT %QW429      : INT;
  ob3_c10         AT %QW430      : INT;
  ob3_c11         AT %QW431      : INT;
  ob3_c12         AT %QW432      : INT;
  ob3_c13         AT %QW433      : INT;
  ob3_c14         AT %QW434      : INT;
  ob3_c15         AT %QW435      : INT;
  ob3_c16         AT %QW436      : INT;
  ob3_c17         AT %QW437      : INT;
  ob3_c18         AT %QW438      : INT;
  ob3_c19         AT %QW439      : INT;

  ort1_c0         AT %QW440      : INT;
  ort1_c1         AT %QW441      : INT;
  ort1_c2         AT %QW442      : INT;
  ort1_c3         AT %QW443      : INT;
  ort1_c4         AT %QW444      : INT;
  ort1_c5         AT %QW445      : INT;
  ort1_c6         AT %QW446      : INT;
  ort1_c7         AT %QW447      : INT;
  ort1_c8         AT %QW448      : INT;
  ort1_c9         AT %QW449      : INT;
  ort1_c10        AT %QW450      : INT;
  ort1_c11        AT %QW451      : INT;
  ort1_c12        AT %QW452      : INT;
  ort1_c13        AT %QW453      : INT;
  ort1_c14        AT %QW454      : INT;
  ort1_c15        AT %QW455      : INT;
  ort1_c16        AT %QW456      : INT;
  ort1_c17        AT %QW457      : INT;
  ort1_c18        AT %QW458      : INT;
  ort1_c19        AT %QW459      : INT;
  ort2_c0         AT %QW460      : INT;
  ort2_c1         AT %QW461      : INT;
  ort2_c2         AT %QW462      : INT;
  ort2_c3         AT %QW463      : INT;
  ort2_c4         AT %QW464      : INT;
  ort2_c5         AT %QW465      : INT;
  ort2_c6         AT %QW466      : INT;
  ort2_c7         AT %QW467      : INT;
  ort2_c8         AT %QW468      : INT;
  ort2_c9         AT %QW469      : INT;
  ort2_c10        AT %QW470      : INT;
  ort2_c11        AT %QW471      : INT;
  ort2_c12        AT %QW472      : INT;
  ort2_c13        AT %QW473      : INT;
  ort2_c14        AT %QW474      : INT;
  ort2_c15        AT %QW475      : INT;
  ort2_c16        AT %QW476      : INT;
  ort2_c17        AT %QW477      : INT;
  ort2_c18        AT %QW478      : INT;
  ort2_c19        AT %QW479      : INT;
  ort3_c0         AT %QW480      : INT;
  ort3_c1         AT %QW481      : INT;
  ort3_c2         AT %QW482      : INT;
  ort3_c3         AT %QW483      : INT;
  ort3_c4         AT %QW484      : INT;
  ort3_c5         AT %QW485      : INT;
  ort3_c6         AT %QW486      : INT;
  ort3_c7         AT %QW487      : INT;
  ort3_c8         AT %QW488      : INT;
  ort3_c9         AT %QW489      : INT;
  ort3_c10        AT %QW490      : INT;
  ort3_c11        AT %QW491      : INT;
  ort3_c12        AT %QW492      : INT;
  ort3_c13        AT %QW493      : INT;
  ort3_c14        AT %QW494      : INT;
  ort3_c15        AT %QW495      : INT;
  ort3_c16        AT %QW496      : INT;
  ort3_c17        AT %QW497      : INT;
  ort3_c18        AT %QW498      : INT;
  ort3_c19        AT %QW499      : INT;

  induct1_cmd  AT %QW100      : INT;
  induct1_ref  AT %QW101      : INT;
  induct1_load AT %QW102      : INT;
  induct1_fb   AT %IW105      : INT;
  induct2_cmd  AT %QW103      : INT;
  induct2_ref  AT %QW104      : INT;
  induct2_load AT %QW105      : INT;
  induct2_fb   AT %IW114      : INT;
  induct3_cmd  AT %QW106      : INT;
  induct3_ref  AT %QW107      : INT;
  induct3_load AT %QW108      : INT;
  induct3_fb   AT %IW123      : INT;
  outbnd1_cmd  AT %QW109      : INT;
  outbnd1_ref  AT %QW110      : INT;
  outbnd1_load AT %QW111      : INT;
  outbnd1_fb   AT %IW132      : INT;
  outbnd2_cmd  AT %QW112      : INT;
  outbnd2_ref  AT %QW113      : INT;
  outbnd2_load AT %QW114      : INT;
  outbnd2_fb   AT %IW141      : INT;
  outbnd3_cmd  AT %QW115      : INT;
  outbnd3_ref  AT %QW116      : INT;
  outbnd3_load AT %QW117      : INT;
  outbnd3_fb   AT %IW150      : INT;
  scan1_trig   AT %QW118      : INT;
  scan1_serial AT %QW119      : INT;
  scan1_seed   AT %QW120      : INT;
  scan1_nrrate AT %QW121      : INT;
  scan1_result AT %IW158      : INT;
  scan1_bc     AT %IW159      : INT;
  scan1_status AT %IW160      : INT;
  scan1_len    AT %IW161      : INT;
  scan1_nonce  AT %IW164      : INT;
  scan2_trig   AT %QW122      : INT;
  scan2_serial AT %QW123      : INT;
  scan2_seed   AT %QW124      : INT;
  scan2_nrrate AT %QW125      : INT;
  scan2_result AT %IW169      : INT;
  scan2_bc     AT %IW170      : INT;
  scan2_status AT %IW171      : INT;
  scan2_len    AT %IW172      : INT;
  scan2_nonce  AT %IW175      : INT;
  scan3_trig   AT %QW126      : INT;
  scan3_serial AT %QW127      : INT;
  scan3_seed   AT %QW128      : INT;
  scan3_nrrate AT %QW129      : INT;
  scan3_result AT %IW180      : INT;
  scan3_bc     AT %IW181      : INT;
  scan3_status AT %IW182      : INT;
  scan3_len    AT %IW183      : INT;
  scan3_nonce  AT %IW186      : INT;
END_VAR

VAR
  ib1 : BELT_T;
  ib2 : BELT_T;
  ib3 : BELT_T;
  rt1 : BELT_T;
  rt2 : BELT_T;
  rt3 : BELT_T;
  ob1 : BELT_T;
  ob2 : BELT_T;
  ob3 : BELT_T;
  ort1 : BELT_T;
  ort2 : BELT_T;
  ort3 : BELT_T;
  acc_i1, acc_i2, acc_i3 : REAL := 0.0;
  acc_o1, acc_o2, acc_o3 : REAL := 0.0;
  tmr1, tmr2, tmr3 : INT := 0;
  last_tun_1, last_tun_2, last_tun_3 : INT := 0;
  i, dest, obelt, door, bc, occ : INT;
  jam_lat_1, jam_lat_2, jam_lat_3 : BOOL := FALSE;
  sts       : INT := 0;
  frst_tmr  : INT := 0;
  tun_pkg_1, tun_pkg_2, tun_pkg_3 : INT := 0;
  tun_seq_1, tun_seq_2, tun_seq_3 : INT := 0;
  tun_wait_1, tun_wait_2, tun_wait_3 : BOOL := FALSE;
  init_done : BOOL := FALSE;
  reset_nonce : INT := 0;
  xle_cmd_seen, xle_route_dest : INT := 0;
  xle_inducted : BOOL := FALSE;
END_VAR

(* reset: clears init_done so the block below re-runs this scan *)
IF reset_cmd AND scanner_state = 0 THEN
  init_done := FALSE;
END_IF;
reset_cmd := FALSE;

IF NOT init_done THEN
  speed_sp_1 := 200; speed_sp_2 := 200; speed_sp_3 := 200;
  ob_speed_1 := 233; ob_speed_2 := 233; ob_speed_3 := 233;
  min_gap_sp := 2;
  rate_sp_1  := 14; rate_sp_2 := 14; rate_sp_3 := 14;
  noread_sp  := 30;
  serial_next := 1;
  prog_hash := 24112;

  (* master_seed is the root of the run. The controller no longer draws
     destinations or no-reads itself: both moved to the camera tunnels,
     which are seeded from this value. It is kept and forwarded rather
     than used here. *)
  IF master_seed <= 0 OR master_seed > 999 THEN
    master_seed := 137;
  END_IF;

  (* clear process state. Without this a reset would leave packages on
     the belts and counters mid-run, and replay would not be replay. *)
  scan_ct := 0;
  shift_ct_1 := 0;
  shift_ct_2 := 0;
  shift_ct_3 := 0;
  noread_ct := 0; coll_ct := 0; jam_ct := 0; missort_ct := 0;
  recirc_ct := 0; nohome_ct := 0; inducted_ct := 0;
  div_act_1 := 0;
  div_act_2 := 0;
  div_act_3 := 0;
  scan_code_1 := 0;
  xle_mode := FALSE;
  xle_cmd_seen := xle_cmd_id;
  xle_route_dest := 0;
  xle_inducted := FALSE;
  xle_ack_id := 0; xle_state := 0; xle_reason := 0;
  xle_actual := 0; xle_package := 0;
  acc_i1 := 0.0; tmr1 := 0; jam_lat_1 := FALSE;
  acc_o1 := 0.0;
  scan_code_2 := 0;
  acc_i2 := 0.0; tmr2 := 0; jam_lat_2 := FALSE;
  acc_o2 := 0.0;
  scan_code_3 := 0;
  acc_i3 := 0.0; tmr3 := 0; jam_lat_3 := FALSE;
  acc_o3 := 0.0;
  tr11_ct := 0; tr11_bad := 0;
  tr12_ct := 0; tr12_bad := 0;
  tr13_ct := 0; tr13_bad := 0;
  tr21_ct := 0; tr21_bad := 0;
  tr22_ct := 0; tr22_bad := 0;
  tr23_ct := 0; tr23_bad := 0;
  tr31_ct := 0; tr31_bad := 0;
  tr32_ct := 0; tr32_bad := 0;
  tr33_ct := 0; tr33_bad := 0;
  FOR i := 0 TO 19 DO
    ib1[i] := 0; rt1[i] := 0;
    ob1[i] := 0; ort1[i] := 0;
    ib2[i] := 0; rt2[i] := 0;
    ob2[i] := 0; ort2[i] := 0;
    ib3[i] := 0; rt3[i] := 0;
    ob3[i] := 0; ort3[i] := 0;
  END_FOR;
  induct1_load := 0;
  induct2_load := 0;
  induct3_load := 0;
  outbnd1_load := 0;
  outbnd2_load := 0;
  outbnd3_load := 0;
  frst_tmr := 0;
  multiple_ct := 0; oversize_ct := 0; duplicate_ct := 0;
  invalid_ct := 0; scan_late_ct := 0;
  tun_pkg_1 := 0; tun_seq_1 := 0; tun_wait_1 := FALSE;
  tun_pkg_2 := 0; tun_seq_2 := 0; tun_wait_2 := FALSE;
  tun_pkg_3 := 0; tun_seq_3 := 0; tun_wait_3 := FALSE;
  reset_nonce := reset_nonce + 1;
  IF reset_nonce > 30000 THEN reset_nonce := 1; END_IF;
  xle_run_nonce := reset_nonce;
  scanner_state := 1; scanner_wait := 0;
  scanner_fault_mask := 0; scanner_ack_mask := 0;
  scan1_trig := 32766; scan1_serial := reset_nonce;
  scan2_trig := 32766; scan2_serial := reset_nonce;
  scan3_trig := 32766; scan3_serial := reset_nonce;
  jam_alarm := FALSE; coll_alarm := FALSE;
  noread_alarm := FALSE; nohome_alarm := FALSE;
  auto_mode := TRUE;
  lane1_run := TRUE; lane2_run := TRUE; lane3_run := TRUE;
  ob1_run := TRUE; ob2_run := TRUE; ob3_run := TRUE;
  init_done := TRUE;
END_IF;

(* logical clock. Wraps at INT max; a run is not expected to reach it,
   and a wrap is visible as a discontinuity rather than silently wrong. *)
IF scan_ct < 32000 THEN
  scan_ct := scan_ct + 1;
ELSE
  scan_ct := 0;
END_IF;

(* operator fault reset: latch the request into a held countdown so the
   bit survives long enough for the drives to sample it *)
IF fault_reset THEN
  frst_tmr := 10;
  fault_reset := FALSE;
END_IF;
IF frst_tmr > 0 THEN
  frst_tmr := frst_tmr - 1;
END_IF;

(* belt load, published to each drive *)
  occ := 0;
  FOR i := 0 TO 19 DO
    IF ib1[i] <> 0 THEN occ := occ + 1; END_IF;
  END_FOR;
  induct1_load := occ;
  occ := 0;
  FOR i := 0 TO 19 DO
    IF ib2[i] <> 0 THEN occ := occ + 1; END_IF;
  END_FOR;
  induct2_load := occ;
  occ := 0;
  FOR i := 0 TO 19 DO
    IF ib3[i] <> 0 THEN occ := occ + 1; END_IF;
  END_FOR;
  induct3_load := occ;
  occ := 0;
  FOR i := 0 TO 19 DO
    IF ob1[i] <> 0 THEN occ := occ + 1; END_IF;
  END_FOR;
  outbnd1_load := occ;
  occ := 0;
  FOR i := 0 TO 19 DO
    IF ob2[i] <> 0 THEN occ := occ + 1; END_IF;
  END_FOR;
  outbnd2_load := occ;
  occ := 0;
  FOR i := 0 TO 19 DO
    IF ob3[i] <> 0 THEN occ := occ + 1; END_IF;
  END_FOR;
  outbnd3_load := occ;

(* drive commands. Bit 2 is the fault reset and is asserted in both
   branches: a faulted drive is not running, so a reset that only
   reaches it while running would never clear anything. *)
IF sorter_run AND lane1_run THEN
  IF frst_tmr > 0 THEN induct1_cmd := 7; ELSE induct1_cmd := 3; END_IF;
  induct1_ref := speed_sp_1;
ELSE
  IF frst_tmr > 0 THEN induct1_cmd := 4; ELSE induct1_cmd := 0; END_IF;
  induct1_ref := 0;
END_IF;
IF sorter_run AND lane2_run THEN
  IF frst_tmr > 0 THEN induct2_cmd := 7; ELSE induct2_cmd := 3; END_IF;
  induct2_ref := speed_sp_2;
ELSE
  IF frst_tmr > 0 THEN induct2_cmd := 4; ELSE induct2_cmd := 0; END_IF;
  induct2_ref := 0;
END_IF;
IF sorter_run AND lane3_run THEN
  IF frst_tmr > 0 THEN induct3_cmd := 7; ELSE induct3_cmd := 3; END_IF;
  induct3_ref := speed_sp_3;
ELSE
  IF frst_tmr > 0 THEN induct3_cmd := 4; ELSE induct3_cmd := 0; END_IF;
  induct3_ref := 0;
END_IF;
IF sorter_run AND ob1_run THEN
  IF frst_tmr > 0 THEN outbnd1_cmd := 7; ELSE outbnd1_cmd := 3; END_IF;
  outbnd1_ref := ob_speed_1;
ELSE
  IF frst_tmr > 0 THEN outbnd1_cmd := 4; ELSE outbnd1_cmd := 0; END_IF;
  outbnd1_ref := 0;
END_IF;
IF sorter_run AND ob2_run THEN
  IF frst_tmr > 0 THEN outbnd2_cmd := 7; ELSE outbnd2_cmd := 3; END_IF;
  outbnd2_ref := ob_speed_2;
ELSE
  IF frst_tmr > 0 THEN outbnd2_cmd := 4; ELSE outbnd2_cmd := 0; END_IF;
  outbnd2_ref := 0;
END_IF;
IF sorter_run AND ob3_run THEN
  IF frst_tmr > 0 THEN outbnd3_cmd := 7; ELSE outbnd3_cmd := 3; END_IF;
  outbnd3_ref := ob_speed_3;
ELSE
  IF frst_tmr > 0 THEN outbnd3_cmd := 4; ELSE outbnd3_cmd := 0; END_IF;
  outbnd3_ref := 0;
END_IF;

(* ---------- camera tunnels ---------- *)
scan1_seed := master_seed; scan2_seed := master_seed; scan3_seed := master_seed;
scan1_nrrate := noread_sp; scan2_nrrate := noread_sp; scan3_nrrate := noread_sp;
IF scanner_state = 1 OR scanner_state = 2 THEN
  scanner_ack_mask := 0;
  IF scanner_state = 1 THEN
    IF scan1_result = 32766 AND scan1_status = 7 AND scan1_nonce = reset_nonce THEN scanner_ack_mask := scanner_ack_mask + 1; END_IF;
    IF scan2_result = 32766 AND scan2_status = 7 AND scan2_nonce = reset_nonce THEN scanner_ack_mask := scanner_ack_mask + 2; END_IF;
    IF scan3_result = 32766 AND scan3_status = 7 AND scan3_nonce = reset_nonce THEN scanner_ack_mask := scanner_ack_mask + 4; END_IF;
  ELSE
    IF scan1_result = 32767 AND scan1_status = 6 AND scan1_nonce = reset_nonce THEN scanner_ack_mask := scanner_ack_mask + 1; END_IF;
    IF scan2_result = 32767 AND scan2_status = 6 AND scan2_nonce = reset_nonce THEN scanner_ack_mask := scanner_ack_mask + 2; END_IF;
    IF scan3_result = 32767 AND scan3_status = 6 AND scan3_nonce = reset_nonce THEN scanner_ack_mask := scanner_ack_mask + 4; END_IF;
  END_IF;
  IF scanner_ack_mask = 7 THEN
    scanner_wait := 0;
    IF scanner_state = 1 THEN
      scanner_state := 2;
      scan1_trig := 32767; scan2_trig := 32767; scan3_trig := 32767;
    ELSE
      scanner_state := 0; scanner_fault_mask := 0;
      scan1_trig := 0; scan2_trig := 0; scan3_trig := 0;
    END_IF;
  ELSE
    scanner_wait := scanner_wait + 1;
    IF scanner_wait >= 200 THEN
      scanner_fault_mask := 7 - scanner_ack_mask;
      scanner_state := 3;
      sorter_run := FALSE;
    END_IF;
  END_IF;
ELSIF scanner_state = 3 THEN
  sorter_run := FALSE;
  IF scanner_fault_ack THEN scanner_state := 4; END_IF;
ELSIF scanner_state = 4 THEN
  sorter_run := FALSE;
  IF scanner_retry THEN
    reset_nonce := reset_nonce + 1;
    IF reset_nonce > 30000 THEN reset_nonce := 1; END_IF;
    xle_run_nonce := reset_nonce;
    scanner_state := 1; scanner_wait := 0; scanner_ack_mask := 0;
    scan1_trig := 32766; scan1_serial := reset_nonce;
    scan2_trig := 32766; scan2_serial := reset_nonce;
    scan3_trig := 32766; scan3_serial := reset_nonce;
  END_IF;
ELSE
(* tunnel 1: request a read on arrival, apply the answer when
   it comes back. Identity crosses a network hop and takes time, so
   a package can leave before its result arrives. That is a late
   scan, which is not the same thing as a failed read. *)
scan1_seed := master_seed;
scan1_nrrate := noread_sp;
IF ib1[10] = 0 OR ib1[10] <> tun_pkg_1 THEN
  IF tun_wait_1 THEN
    scan_late_ct := scan_late_ct + 1;
    tun_wait_1 := FALSE;
  END_IF;
  tun_pkg_1 := ib1[10];
  IF ib1[10] <> 0 THEN
    tun_seq_1 := tun_seq_1 + 1;
    IF tun_seq_1 > 30000 THEN tun_seq_1 := 1; END_IF;
    scan1_trig := tun_seq_1;
    scan1_serial := ib1[10];
    tun_wait_1 := TRUE;
  END_IF;
ELSIF tun_wait_1 AND scan1_result = tun_seq_1 AND scan1_nonce = reset_nonce THEN
  tun_wait_1 := FALSE;
  bc := scan1_bc;
  sts := scan1_status;
  scan_code_1 := bc;
  IF sts = 0 OR sts = 3 OR sts = 4 THEN
    IF sts = 3 THEN oversize_ct := oversize_ct + 1; END_IF;
    IF sts = 4 THEN duplicate_ct := duplicate_ct + 1; END_IF;
    (* the package becomes what the tunnel says it is. Truth and
       belief part company here: the door scan compares this against
       the trailer it actually ends up in. *)
    ib1[10] := bc;
    tun_pkg_1 := bc;
    IF xle_mode THEN
      xle_package := bc;
      xle_state := 0; xle_reason := 0; xle_actual := 0;
      xle_route_dest := 0;
      rt1[10] := 0;
    ELSE
      dest  := bc / 1000;
      obelt := ((dest - 1) / 3) + 1;
      IF obelt = 1 THEN rt1[10] := 14;
      ELSIF obelt = 2 THEN rt1[10] := 16;
      ELSIF obelt = 3 THEN rt1[10] := 18;
      ELSE rt1[10] := 0;
      END_IF;
    END_IF;
  ELSE
    (* no usable identity: the package keeps its serial, rides to the
       end of the belt and recirculates. *)
    rt1[10] := 0;
    IF sts = 1 THEN
      noread_ct := noread_ct + 1;
      noread_alarm := TRUE;
    ELSIF sts = 2 THEN
      multiple_ct := multiple_ct + 1;
    ELSIF sts = 5 THEN
      invalid_ct := invalid_ct + 1;
    END_IF;
  END_IF;
END_IF;

(* tunnel 2: request a read on arrival, apply the answer when
   it comes back. Identity crosses a network hop and takes time, so
   a package can leave before its result arrives. That is a late
   scan, which is not the same thing as a failed read. *)
scan2_seed := master_seed;
scan2_nrrate := noread_sp;
IF ib2[10] = 0 OR ib2[10] <> tun_pkg_2 THEN
  IF tun_wait_2 THEN
    scan_late_ct := scan_late_ct + 1;
    tun_wait_2 := FALSE;
  END_IF;
  tun_pkg_2 := ib2[10];
  IF ib2[10] <> 0 THEN
    tun_seq_2 := tun_seq_2 + 1;
    IF tun_seq_2 > 30000 THEN tun_seq_2 := 1; END_IF;
    scan2_trig := tun_seq_2;
    scan2_serial := ib2[10];
    tun_wait_2 := TRUE;
  END_IF;
ELSIF tun_wait_2 AND scan2_result = tun_seq_2 AND scan2_nonce = reset_nonce THEN
  tun_wait_2 := FALSE;
  bc := scan2_bc;
  sts := scan2_status;
  scan_code_2 := bc;
  IF sts = 0 OR sts = 3 OR sts = 4 THEN
    IF sts = 3 THEN oversize_ct := oversize_ct + 1; END_IF;
    IF sts = 4 THEN duplicate_ct := duplicate_ct + 1; END_IF;
    (* the package becomes what the tunnel says it is. Truth and
       belief part company here: the door scan compares this against
       the trailer it actually ends up in. *)
    ib2[10] := bc;
    tun_pkg_2 := bc;
    dest  := bc / 1000;
    obelt := ((dest - 1) / 3) + 1;
    IF obelt = 1 THEN rt2[10] := 14;
    ELSIF obelt = 2 THEN rt2[10] := 16;
    ELSIF obelt = 3 THEN rt2[10] := 18;
    ELSE rt2[10] := 0;
    END_IF;
  ELSE
    (* no usable identity: the package keeps its serial, rides to the
       end of the belt and recirculates. *)
    rt2[10] := 0;
    IF sts = 1 THEN
      noread_ct := noread_ct + 1;
      noread_alarm := TRUE;
    ELSIF sts = 2 THEN
      multiple_ct := multiple_ct + 1;
    ELSIF sts = 5 THEN
      invalid_ct := invalid_ct + 1;
    END_IF;
  END_IF;
END_IF;

(* tunnel 3: request a read on arrival, apply the answer when
   it comes back. Identity crosses a network hop and takes time, so
   a package can leave before its result arrives. That is a late
   scan, which is not the same thing as a failed read. *)
scan3_seed := master_seed;
scan3_nrrate := noread_sp;
IF ib3[10] = 0 OR ib3[10] <> tun_pkg_3 THEN
  IF tun_wait_3 THEN
    scan_late_ct := scan_late_ct + 1;
    tun_wait_3 := FALSE;
  END_IF;
  tun_pkg_3 := ib3[10];
  IF ib3[10] <> 0 THEN
    tun_seq_3 := tun_seq_3 + 1;
    IF tun_seq_3 > 30000 THEN tun_seq_3 := 1; END_IF;
    scan3_trig := tun_seq_3;
    scan3_serial := ib3[10];
    tun_wait_3 := TRUE;
  END_IF;
ELSIF tun_wait_3 AND scan3_result = tun_seq_3 AND scan3_nonce = reset_nonce THEN
  tun_wait_3 := FALSE;
  bc := scan3_bc;
  sts := scan3_status;
  scan_code_3 := bc;
  IF sts = 0 OR sts = 3 OR sts = 4 THEN
    IF sts = 3 THEN oversize_ct := oversize_ct + 1; END_IF;
    IF sts = 4 THEN duplicate_ct := duplicate_ct + 1; END_IF;
    (* the package becomes what the tunnel says it is. Truth and
       belief part company here: the door scan compares this against
       the trailer it actually ends up in. *)
    ib3[10] := bc;
    tun_pkg_3 := bc;
    dest  := bc / 1000;
    obelt := ((dest - 1) / 3) + 1;
    IF obelt = 1 THEN rt3[10] := 14;
    ELSIF obelt = 2 THEN rt3[10] := 16;
    ELSIF obelt = 3 THEN rt3[10] := 18;
    ELSE rt3[10] := 0;
    END_IF;
  ELSE
    (* no usable identity: the package keeps its serial, rides to the
       end of the belt and recirculates. *)
    rt3[10] := 0;
    IF sts = 1 THEN
      noread_ct := noread_ct + 1;
      noread_alarm := TRUE;
    ELSIF sts = 2 THEN
      multiple_ct := multiple_ct + 1;
    ELSIF sts = 5 THEN
      invalid_ct := invalid_ct + 1;
    END_IF;
  END_IF;
END_IF;


(* Accept one command for the current scanned package before cell 14.
   A package without a valid command retains route zero and recirculates. *)
IF xle_mode AND xle_cmd_id <> 0 AND xle_cmd_id <> xle_cmd_seen THEN
  xle_cmd_seen := xle_cmd_id;
  xle_ack_id := xle_cmd_id;
  xle_state := 4; xle_reason := 2; xle_actual := 0;
  IF xle_cmd_nonce = reset_nonce AND xle_cmd_bc = xle_package AND
     xle_package <> 0 AND xle_cmd_dest >= 1 AND xle_cmd_dest <= 9 THEN
    FOR i := 10 TO 13 DO
      IF ib1[i] = xle_package THEN
        xle_route_dest := xle_cmd_dest;
        obelt := ((xle_route_dest - 1) / 3) + 1;
        IF obelt = 1 THEN rt1[i] := 14;
        ELSIF obelt = 2 THEN rt1[i] := 16;
        ELSE rt1[i] := 18;
        END_IF;
        xle_state := 1; xle_reason := 0;
      END_IF;
    END_FOR;
  END_IF;
END_IF;

(* ---------- induct lane 1 ---------- *)
acc_i1 := acc_i1 + (INT_TO_REAL(induct1_fb) / 1750.0);
IF acc_i1 >= 1.0 THEN
  acc_i1 := acc_i1 - 1.0;
  IF shift_ct_1 < 32000 THEN
    shift_ct_1 := shift_ct_1 + 1;
  ELSE
    shift_ct_1 := 0;
  END_IF;

  (* undiverted off the end of the belt: a recirc, not a jam *)
  IF ib1[19] <> 0 THEN
    recirc_ct := recirc_ct + 1;
    IF xle_mode AND ib1[19] = xle_package AND xle_state = 0 THEN
      xle_state := 5; xle_reason := 1;
    END_IF;
  END_IF;

  (* jam: the tail of the belt is backing up. Three consecutive
     occupied cells means packages are arriving faster than they
     divert. Edge triggered, so one jam counts once however long
     it persists. Zero under the clean baseline. *)
  IF ib1[19] <> 0 AND ib1[18] <> 0 AND ib1[17] <> 0 THEN
    IF NOT jam_lat_1 THEN
      jam_ct := jam_ct + 1;
      jam_alarm := TRUE;
      jam_lat_1 := TRUE;
    END_IF;
  ELSE
    jam_lat_1 := FALSE;
  END_IF;

  FOR i := 19 TO 1 BY -1 DO
    ib1[i] := ib1[i-1];
    rt1[i] := rt1[i-1];
  END_FOR;
  ib1[0] := 0;
  rt1[0] := 0;

  (* induct if the interval expired and the gap is clear *)
  tmr1 := tmr1 + 1;
  IF tmr1 >= rate_sp_1 THEN
    tmr1 := 0;
    occ := 0;
    FOR i := 0 TO min_gap_sp DO
      IF ib1[i] <> 0 THEN occ := occ + 1; END_IF;
    END_FOR;
    IF occ = 0 AND (NOT xle_mode OR NOT xle_inducted) THEN
      ib1[0] := serial_next;
      IF xle_mode THEN xle_inducted := TRUE; END_IF;
      serial_next := serial_next + 1;
      IF serial_next > 999 THEN serial_next := 1; END_IF;
      inducted_ct := inducted_ct + 1;
    END_IF;
  END_IF;

  (* induct divert points *)
  l1_div1 := FALSE;
  IF auto_mode AND ib1[14] <> 0 AND rt1[14] = 14 THEN
    l1_div1 := TRUE;
    div_act_1 := div_act_1 + 1;
    IF xle_mode AND ib1[14] = xle_package THEN xle_state := 2; END_IF;
    IF ob1[2] <> 0 THEN
      coll_ct := coll_ct + 1;
      coll_alarm := TRUE;
      IF xle_mode AND ib1[14] = xle_package THEN xle_state := 4; xle_reason := 3; END_IF;
    ELSE
      ob1[2] := ib1[14];
      (* carry the door target onto the outbound belt *)
      dest := ib1[14] / 1000;
      IF xle_mode AND ib1[14] = xle_package THEN dest := xle_route_dest; END_IF;
      door := ((dest - 1) MOD 3) + 1;
      IF door = 1 THEN ort1[2] := 12;
      ELSIF door = 2 THEN ort1[2] := 15;
      ELSIF door = 3 THEN ort1[2] := 18;
      ELSE ort1[2] := 0;
      END_IF;
    END_IF;
    ib1[14] := 0;
    rt1[14] := 0;
  END_IF;
  l1_div2 := FALSE;
  IF auto_mode AND ib1[16] <> 0 AND rt1[16] = 16 THEN
    l1_div2 := TRUE;
    div_act_2 := div_act_2 + 1;
    IF xle_mode AND ib1[16] = xle_package THEN xle_state := 2; END_IF;
    IF ob2[2] <> 0 THEN
      coll_ct := coll_ct + 1;
      coll_alarm := TRUE;
      IF xle_mode AND ib1[16] = xle_package THEN xle_state := 4; xle_reason := 3; END_IF;
    ELSE
      ob2[2] := ib1[16];
      (* carry the door target onto the outbound belt *)
      dest := ib1[16] / 1000;
      IF xle_mode AND ib1[16] = xle_package THEN dest := xle_route_dest; END_IF;
      door := ((dest - 1) MOD 3) + 1;
      IF door = 1 THEN ort2[2] := 12;
      ELSIF door = 2 THEN ort2[2] := 15;
      ELSIF door = 3 THEN ort2[2] := 18;
      ELSE ort2[2] := 0;
      END_IF;
    END_IF;
    ib1[16] := 0;
    rt1[16] := 0;
  END_IF;
  l1_div3 := FALSE;
  IF auto_mode AND ib1[18] <> 0 AND rt1[18] = 18 THEN
    l1_div3 := TRUE;
    div_act_3 := div_act_3 + 1;
    IF xle_mode AND ib1[18] = xle_package THEN xle_state := 2; END_IF;
    IF ob3[2] <> 0 THEN
      coll_ct := coll_ct + 1;
      coll_alarm := TRUE;
      IF xle_mode AND ib1[18] = xle_package THEN xle_state := 4; xle_reason := 3; END_IF;
    ELSE
      ob3[2] := ib1[18];
      (* carry the door target onto the outbound belt *)
      dest := ib1[18] / 1000;
      IF xle_mode AND ib1[18] = xle_package THEN dest := xle_route_dest; END_IF;
      door := ((dest - 1) MOD 3) + 1;
      IF door = 1 THEN ort3[2] := 12;
      ELSIF door = 2 THEN ort3[2] := 15;
      ELSIF door = 3 THEN ort3[2] := 18;
      ELSE ort3[2] := 0;
      END_IF;
    END_IF;
    ib1[18] := 0;
    rt1[18] := 0;
  END_IF;
END_IF;

(* Publish the tunnel sensor event in the scan that moves a package into
   cell 10. The camera result is still consumed at the start of the next
   scan, before another belt shift can move this package away. *)
IF ib1[10] <> 0 AND ib1[10] <> tun_pkg_1 THEN
  IF tun_wait_1 THEN scan_late_ct := scan_late_ct + 1; END_IF;
  tun_pkg_1 := ib1[10];
  tun_seq_1 := tun_seq_1 + 1;
  IF tun_seq_1 > 30000 THEN tun_seq_1 := 1; END_IF;
  scan1_trig := tun_seq_1;
  scan1_serial := ib1[10];
  tun_wait_1 := TRUE;
END_IF;

(* ---------- induct lane 2 ---------- *)
acc_i2 := acc_i2 + (INT_TO_REAL(induct2_fb) / 1750.0);
IF acc_i2 >= 1.0 THEN
  acc_i2 := acc_i2 - 1.0;
  IF shift_ct_2 < 32000 THEN
    shift_ct_2 := shift_ct_2 + 1;
  ELSE
    shift_ct_2 := 0;
  END_IF;

  (* undiverted off the end of the belt: a recirc, not a jam *)
  IF ib2[19] <> 0 THEN
    recirc_ct := recirc_ct + 1;
  END_IF;

  (* jam: the tail of the belt is backing up. Three consecutive
     occupied cells means packages are arriving faster than they
     divert. Edge triggered, so one jam counts once however long
     it persists. Zero under the clean baseline. *)
  IF ib2[19] <> 0 AND ib2[18] <> 0 AND ib2[17] <> 0 THEN
    IF NOT jam_lat_2 THEN
      jam_ct := jam_ct + 1;
      jam_alarm := TRUE;
      jam_lat_2 := TRUE;
    END_IF;
  ELSE
    jam_lat_2 := FALSE;
  END_IF;

  FOR i := 19 TO 1 BY -1 DO
    ib2[i] := ib2[i-1];
    rt2[i] := rt2[i-1];
  END_FOR;
  ib2[0] := 0;
  rt2[0] := 0;

  (* induct if the interval expired and the gap is clear *)
  tmr2 := tmr2 + 1;
  IF tmr2 >= rate_sp_2 THEN
    tmr2 := 0;
    occ := 0;
    FOR i := 0 TO min_gap_sp DO
      IF ib2[i] <> 0 THEN occ := occ + 1; END_IF;
    END_FOR;
    IF occ = 0 THEN
      ib2[0] := serial_next;
      serial_next := serial_next + 1;
      IF serial_next > 999 THEN serial_next := 1; END_IF;
      inducted_ct := inducted_ct + 1;
    END_IF;
  END_IF;

  (* induct divert points *)
  l2_div1 := FALSE;
  IF auto_mode AND ib2[14] <> 0 AND rt2[14] = 14 THEN
    l2_div1 := TRUE;
    div_act_1 := div_act_1 + 1;
    IF ob1[5] <> 0 THEN
      coll_ct := coll_ct + 1;
      coll_alarm := TRUE;
    ELSE
      ob1[5] := ib2[14];
      (* carry the door target onto the outbound belt *)
      dest := ib2[14] / 1000;
      door := ((dest - 1) MOD 3) + 1;
      IF door = 1 THEN ort1[5] := 12;
      ELSIF door = 2 THEN ort1[5] := 15;
      ELSIF door = 3 THEN ort1[5] := 18;
      ELSE ort1[5] := 0;
      END_IF;
    END_IF;
    ib2[14] := 0;
    rt2[14] := 0;
  END_IF;
  l2_div2 := FALSE;
  IF auto_mode AND ib2[16] <> 0 AND rt2[16] = 16 THEN
    l2_div2 := TRUE;
    div_act_2 := div_act_2 + 1;
    IF ob2[5] <> 0 THEN
      coll_ct := coll_ct + 1;
      coll_alarm := TRUE;
    ELSE
      ob2[5] := ib2[16];
      (* carry the door target onto the outbound belt *)
      dest := ib2[16] / 1000;
      door := ((dest - 1) MOD 3) + 1;
      IF door = 1 THEN ort2[5] := 12;
      ELSIF door = 2 THEN ort2[5] := 15;
      ELSIF door = 3 THEN ort2[5] := 18;
      ELSE ort2[5] := 0;
      END_IF;
    END_IF;
    ib2[16] := 0;
    rt2[16] := 0;
  END_IF;
  l2_div3 := FALSE;
  IF auto_mode AND ib2[18] <> 0 AND rt2[18] = 18 THEN
    l2_div3 := TRUE;
    div_act_3 := div_act_3 + 1;
    IF ob3[5] <> 0 THEN
      coll_ct := coll_ct + 1;
      coll_alarm := TRUE;
    ELSE
      ob3[5] := ib2[18];
      (* carry the door target onto the outbound belt *)
      dest := ib2[18] / 1000;
      door := ((dest - 1) MOD 3) + 1;
      IF door = 1 THEN ort3[5] := 12;
      ELSIF door = 2 THEN ort3[5] := 15;
      ELSIF door = 3 THEN ort3[5] := 18;
      ELSE ort3[5] := 0;
      END_IF;
    END_IF;
    ib2[18] := 0;
    rt2[18] := 0;
  END_IF;
END_IF;

IF ib2[10] <> 0 AND ib2[10] <> tun_pkg_2 THEN
  IF tun_wait_2 THEN scan_late_ct := scan_late_ct + 1; END_IF;
  tun_pkg_2 := ib2[10];
  tun_seq_2 := tun_seq_2 + 1;
  IF tun_seq_2 > 30000 THEN tun_seq_2 := 1; END_IF;
  scan2_trig := tun_seq_2;
  scan2_serial := ib2[10];
  tun_wait_2 := TRUE;
END_IF;

(* ---------- induct lane 3 ---------- *)
acc_i3 := acc_i3 + (INT_TO_REAL(induct3_fb) / 1750.0);
IF acc_i3 >= 1.0 THEN
  acc_i3 := acc_i3 - 1.0;
  IF shift_ct_3 < 32000 THEN
    shift_ct_3 := shift_ct_3 + 1;
  ELSE
    shift_ct_3 := 0;
  END_IF;

  (* undiverted off the end of the belt: a recirc, not a jam *)
  IF ib3[19] <> 0 THEN
    recirc_ct := recirc_ct + 1;
  END_IF;

  (* jam: the tail of the belt is backing up. Three consecutive
     occupied cells means packages are arriving faster than they
     divert. Edge triggered, so one jam counts once however long
     it persists. Zero under the clean baseline. *)
  IF ib3[19] <> 0 AND ib3[18] <> 0 AND ib3[17] <> 0 THEN
    IF NOT jam_lat_3 THEN
      jam_ct := jam_ct + 1;
      jam_alarm := TRUE;
      jam_lat_3 := TRUE;
    END_IF;
  ELSE
    jam_lat_3 := FALSE;
  END_IF;

  FOR i := 19 TO 1 BY -1 DO
    ib3[i] := ib3[i-1];
    rt3[i] := rt3[i-1];
  END_FOR;
  ib3[0] := 0;
  rt3[0] := 0;

  (* induct if the interval expired and the gap is clear *)
  tmr3 := tmr3 + 1;
  IF tmr3 >= rate_sp_3 THEN
    tmr3 := 0;
    occ := 0;
    FOR i := 0 TO min_gap_sp DO
      IF ib3[i] <> 0 THEN occ := occ + 1; END_IF;
    END_FOR;
    IF occ = 0 THEN
      ib3[0] := serial_next;
      serial_next := serial_next + 1;
      IF serial_next > 999 THEN serial_next := 1; END_IF;
      inducted_ct := inducted_ct + 1;
    END_IF;
  END_IF;

  (* induct divert points *)
  l3_div1 := FALSE;
  IF auto_mode AND ib3[14] <> 0 AND rt3[14] = 14 THEN
    l3_div1 := TRUE;
    div_act_1 := div_act_1 + 1;
    IF ob1[8] <> 0 THEN
      coll_ct := coll_ct + 1;
      coll_alarm := TRUE;
    ELSE
      ob1[8] := ib3[14];
      (* carry the door target onto the outbound belt *)
      dest := ib3[14] / 1000;
      door := ((dest - 1) MOD 3) + 1;
      IF door = 1 THEN ort1[8] := 12;
      ELSIF door = 2 THEN ort1[8] := 15;
      ELSIF door = 3 THEN ort1[8] := 18;
      ELSE ort1[8] := 0;
      END_IF;
    END_IF;
    ib3[14] := 0;
    rt3[14] := 0;
  END_IF;
  l3_div2 := FALSE;
  IF auto_mode AND ib3[16] <> 0 AND rt3[16] = 16 THEN
    l3_div2 := TRUE;
    div_act_2 := div_act_2 + 1;
    IF ob2[8] <> 0 THEN
      coll_ct := coll_ct + 1;
      coll_alarm := TRUE;
    ELSE
      ob2[8] := ib3[16];
      (* carry the door target onto the outbound belt *)
      dest := ib3[16] / 1000;
      door := ((dest - 1) MOD 3) + 1;
      IF door = 1 THEN ort2[8] := 12;
      ELSIF door = 2 THEN ort2[8] := 15;
      ELSIF door = 3 THEN ort2[8] := 18;
      ELSE ort2[8] := 0;
      END_IF;
    END_IF;
    ib3[16] := 0;
    rt3[16] := 0;
  END_IF;
  l3_div3 := FALSE;
  IF auto_mode AND ib3[18] <> 0 AND rt3[18] = 18 THEN
    l3_div3 := TRUE;
    div_act_3 := div_act_3 + 1;
    IF ob3[8] <> 0 THEN
      coll_ct := coll_ct + 1;
      coll_alarm := TRUE;
    ELSE
      ob3[8] := ib3[18];
      (* carry the door target onto the outbound belt *)
      dest := ib3[18] / 1000;
      door := ((dest - 1) MOD 3) + 1;
      IF door = 1 THEN ort3[8] := 12;
      ELSIF door = 2 THEN ort3[8] := 15;
      ELSIF door = 3 THEN ort3[8] := 18;
      ELSE ort3[8] := 0;
      END_IF;
    END_IF;
    ib3[18] := 0;
    rt3[18] := 0;
  END_IF;
END_IF;

IF ib3[10] <> 0 AND ib3[10] <> tun_pkg_3 THEN
  IF tun_wait_3 THEN scan_late_ct := scan_late_ct + 1; END_IF;
  tun_pkg_3 := ib3[10];
  tun_seq_3 := tun_seq_3 + 1;
  IF tun_seq_3 > 30000 THEN tun_seq_3 := 1; END_IF;
  scan3_trig := tun_seq_3;
  scan3_serial := ib3[10];
  tun_wait_3 := TRUE;
END_IF;

(* ---------- outbound belt 1 ---------- *)
acc_o1 := acc_o1 + (INT_TO_REAL(outbnd1_fb) / 1750.0);
IF acc_o1 >= 1.0 THEN
  acc_o1 := acc_o1 - 1.0;

  (* end of belt: package passed every door *)
  IF ob1[19] <> 0 THEN
    nohome_ct := nohome_ct + 1;
    nohome_alarm := TRUE;
    IF xle_mode AND ob1[19] = xle_package AND xle_state = 2 THEN
      xle_state := 4; xle_reason := 4;
    END_IF;
  END_IF;

  FOR i := 19 TO 1 BY -1 DO
    ob1[i] := ob1[i-1];
    ort1[i] := ort1[i-1];
  END_FOR;
  ob1[0] := 0;
  ort1[0] := 0;

  (* trailer doors: divert and verify against the printed barcode *)
  b1_door1 := FALSE;
  IF auto_mode AND ob1[12] <> 0 AND ort1[12] = 12 THEN
    b1_door1 := TRUE;
    bc := ob1[12];
    dest := bc / 1000;
    tr11_ct := tr11_ct + 1;
    IF xle_mode AND bc = xle_package AND xle_state = 2 THEN
      dest := xle_route_dest;
      xle_state := 3; xle_actual := 1; xle_reason := 0;
    END_IF;
    IF dest <> 1 THEN
      tr11_bad := tr11_bad + 1;
      missort_ct := missort_ct + 1;
      IF xle_mode AND bc = xle_package THEN xle_state := 4; xle_reason := 5; END_IF;
    END_IF;
    ob1[12] := 0;
    ort1[12] := 0;
  END_IF;
  b1_door2 := FALSE;
  IF auto_mode AND ob1[15] <> 0 AND ort1[15] = 15 THEN
    b1_door2 := TRUE;
    bc := ob1[15];
    dest := bc / 1000;
    tr12_ct := tr12_ct + 1;
    IF xle_mode AND bc = xle_package AND xle_state = 2 THEN
      dest := xle_route_dest;
      xle_state := 3; xle_actual := 2; xle_reason := 0;
    END_IF;
    IF dest <> 2 THEN
      tr12_bad := tr12_bad + 1;
      missort_ct := missort_ct + 1;
      IF xle_mode AND bc = xle_package THEN xle_state := 4; xle_reason := 5; END_IF;
    END_IF;
    ob1[15] := 0;
    ort1[15] := 0;
  END_IF;
  b1_door3 := FALSE;
  IF auto_mode AND ob1[18] <> 0 AND ort1[18] = 18 THEN
    b1_door3 := TRUE;
    bc := ob1[18];
    dest := bc / 1000;
    tr13_ct := tr13_ct + 1;
    IF xle_mode AND bc = xle_package AND xle_state = 2 THEN
      dest := xle_route_dest;
      xle_state := 3; xle_actual := 3; xle_reason := 0;
    END_IF;
    IF dest <> 3 THEN
      tr13_bad := tr13_bad + 1;
      missort_ct := missort_ct + 1;
      IF xle_mode AND bc = xle_package THEN xle_state := 4; xle_reason := 5; END_IF;
    END_IF;
    ob1[18] := 0;
    ort1[18] := 0;
  END_IF;
END_IF;

(* ---------- outbound belt 2 ---------- *)
acc_o2 := acc_o2 + (INT_TO_REAL(outbnd2_fb) / 1750.0);
IF acc_o2 >= 1.0 THEN
  acc_o2 := acc_o2 - 1.0;

  (* end of belt: package passed every door *)
  IF ob2[19] <> 0 THEN
    nohome_ct := nohome_ct + 1;
    nohome_alarm := TRUE;
    IF xle_mode AND ob2[19] = xle_package AND xle_state = 2 THEN
      xle_state := 4; xle_reason := 4;
    END_IF;
  END_IF;

  FOR i := 19 TO 1 BY -1 DO
    ob2[i] := ob2[i-1];
    ort2[i] := ort2[i-1];
  END_FOR;
  ob2[0] := 0;
  ort2[0] := 0;

  (* trailer doors: divert and verify against the printed barcode *)
  b2_door1 := FALSE;
  IF auto_mode AND ob2[12] <> 0 AND ort2[12] = 12 THEN
    b2_door1 := TRUE;
    bc := ob2[12];
    dest := bc / 1000;
    tr21_ct := tr21_ct + 1;
    IF xle_mode AND bc = xle_package AND xle_state = 2 THEN
      dest := xle_route_dest;
      xle_state := 3; xle_actual := 4; xle_reason := 0;
    END_IF;
    IF dest <> 4 THEN
      tr21_bad := tr21_bad + 1;
      missort_ct := missort_ct + 1;
      IF xle_mode AND bc = xle_package THEN xle_state := 4; xle_reason := 5; END_IF;
    END_IF;
    ob2[12] := 0;
    ort2[12] := 0;
  END_IF;
  b2_door2 := FALSE;
  IF auto_mode AND ob2[15] <> 0 AND ort2[15] = 15 THEN
    b2_door2 := TRUE;
    bc := ob2[15];
    dest := bc / 1000;
    tr22_ct := tr22_ct + 1;
    IF xle_mode AND bc = xle_package AND xle_state = 2 THEN
      dest := xle_route_dest;
      xle_state := 3; xle_actual := 5; xle_reason := 0;
    END_IF;
    IF dest <> 5 THEN
      tr22_bad := tr22_bad + 1;
      missort_ct := missort_ct + 1;
      IF xle_mode AND bc = xle_package THEN xle_state := 4; xle_reason := 5; END_IF;
    END_IF;
    ob2[15] := 0;
    ort2[15] := 0;
  END_IF;
  b2_door3 := FALSE;
  IF auto_mode AND ob2[18] <> 0 AND ort2[18] = 18 THEN
    b2_door3 := TRUE;
    bc := ob2[18];
    dest := bc / 1000;
    tr23_ct := tr23_ct + 1;
    IF xle_mode AND bc = xle_package AND xle_state = 2 THEN
      dest := xle_route_dest;
      xle_state := 3; xle_actual := 6; xle_reason := 0;
    END_IF;
    IF dest <> 6 THEN
      tr23_bad := tr23_bad + 1;
      missort_ct := missort_ct + 1;
      IF xle_mode AND bc = xle_package THEN xle_state := 4; xle_reason := 5; END_IF;
    END_IF;
    ob2[18] := 0;
    ort2[18] := 0;
  END_IF;
END_IF;

(* ---------- outbound belt 3 ---------- *)
acc_o3 := acc_o3 + (INT_TO_REAL(outbnd3_fb) / 1750.0);
IF acc_o3 >= 1.0 THEN
  acc_o3 := acc_o3 - 1.0;

  (* end of belt: package passed every door *)
  IF ob3[19] <> 0 THEN
    nohome_ct := nohome_ct + 1;
    nohome_alarm := TRUE;
    IF xle_mode AND ob3[19] = xle_package AND xle_state = 2 THEN
      xle_state := 4; xle_reason := 4;
    END_IF;
  END_IF;

  FOR i := 19 TO 1 BY -1 DO
    ob3[i] := ob3[i-1];
    ort3[i] := ort3[i-1];
  END_FOR;
  ob3[0] := 0;
  ort3[0] := 0;

  (* trailer doors: divert and verify against the printed barcode *)
  b3_door1 := FALSE;
  IF auto_mode AND ob3[12] <> 0 AND ort3[12] = 12 THEN
    b3_door1 := TRUE;
    bc := ob3[12];
    dest := bc / 1000;
    tr31_ct := tr31_ct + 1;
    IF xle_mode AND bc = xle_package AND xle_state = 2 THEN
      dest := xle_route_dest;
      xle_state := 3; xle_actual := 7; xle_reason := 0;
    END_IF;
    IF dest <> 7 THEN
      tr31_bad := tr31_bad + 1;
      missort_ct := missort_ct + 1;
      IF xle_mode AND bc = xle_package THEN xle_state := 4; xle_reason := 5; END_IF;
    END_IF;
    ob3[12] := 0;
    ort3[12] := 0;
  END_IF;
  b3_door2 := FALSE;
  IF auto_mode AND ob3[15] <> 0 AND ort3[15] = 15 THEN
    b3_door2 := TRUE;
    bc := ob3[15];
    dest := bc / 1000;
    tr32_ct := tr32_ct + 1;
    IF xle_mode AND bc = xle_package AND xle_state = 2 THEN
      dest := xle_route_dest;
      xle_state := 3; xle_actual := 8; xle_reason := 0;
    END_IF;
    IF dest <> 8 THEN
      tr32_bad := tr32_bad + 1;
      missort_ct := missort_ct + 1;
      IF xle_mode AND bc = xle_package THEN xle_state := 4; xle_reason := 5; END_IF;
    END_IF;
    ob3[15] := 0;
    ort3[15] := 0;
  END_IF;
  b3_door3 := FALSE;
  IF auto_mode AND ob3[18] <> 0 AND ort3[18] = 18 THEN
    b3_door3 := TRUE;
    bc := ob3[18];
    dest := bc / 1000;
    tr33_ct := tr33_ct + 1;
    IF xle_mode AND bc = xle_package AND xle_state = 2 THEN
      dest := xle_route_dest;
      xle_state := 3; xle_actual := 9; xle_reason := 0;
    END_IF;
    IF dest <> 9 THEN
      tr33_bad := tr33_bad + 1;
      missort_ct := missort_ct + 1;
      IF xle_mode AND bc = xle_package THEN xle_state := 4; xle_reason := 5; END_IF;
    END_IF;
    ob3[18] := 0;
    ort3[18] := 0;
  END_IF;
END_IF;

END_IF; (* scanner handshake and fault gate package movement *)
scanner_fault_ack := FALSE;
scanner_retry := FALSE;

(* publish belt state to the exposed register map *)
ib1_c0 := ib1[0];
ib1_c1 := ib1[1];
ib1_c2 := ib1[2];
ib1_c3 := ib1[3];
ib1_c4 := ib1[4];
ib1_c5 := ib1[5];
ib1_c6 := ib1[6];
ib1_c7 := ib1[7];
ib1_c8 := ib1[8];
ib1_c9 := ib1[9];
ib1_c10 := ib1[10];
ib1_c11 := ib1[11];
ib1_c12 := ib1[12];
ib1_c13 := ib1[13];
ib1_c14 := ib1[14];
ib1_c15 := ib1[15];
ib1_c16 := ib1[16];
ib1_c17 := ib1[17];
ib1_c18 := ib1[18];
ib1_c19 := ib1[19];
ib2_c0 := ib2[0];
ib2_c1 := ib2[1];
ib2_c2 := ib2[2];
ib2_c3 := ib2[3];
ib2_c4 := ib2[4];
ib2_c5 := ib2[5];
ib2_c6 := ib2[6];
ib2_c7 := ib2[7];
ib2_c8 := ib2[8];
ib2_c9 := ib2[9];
ib2_c10 := ib2[10];
ib2_c11 := ib2[11];
ib2_c12 := ib2[12];
ib2_c13 := ib2[13];
ib2_c14 := ib2[14];
ib2_c15 := ib2[15];
ib2_c16 := ib2[16];
ib2_c17 := ib2[17];
ib2_c18 := ib2[18];
ib2_c19 := ib2[19];
ib3_c0 := ib3[0];
ib3_c1 := ib3[1];
ib3_c2 := ib3[2];
ib3_c3 := ib3[3];
ib3_c4 := ib3[4];
ib3_c5 := ib3[5];
ib3_c6 := ib3[6];
ib3_c7 := ib3[7];
ib3_c8 := ib3[8];
ib3_c9 := ib3[9];
ib3_c10 := ib3[10];
ib3_c11 := ib3[11];
ib3_c12 := ib3[12];
ib3_c13 := ib3[13];
ib3_c14 := ib3[14];
ib3_c15 := ib3[15];
ib3_c16 := ib3[16];
ib3_c17 := ib3[17];
ib3_c18 := ib3[18];
ib3_c19 := ib3[19];
rt1_c0 := rt1[0];
rt1_c1 := rt1[1];
rt1_c2 := rt1[2];
rt1_c3 := rt1[3];
rt1_c4 := rt1[4];
rt1_c5 := rt1[5];
rt1_c6 := rt1[6];
rt1_c7 := rt1[7];
rt1_c8 := rt1[8];
rt1_c9 := rt1[9];
rt1_c10 := rt1[10];
rt1_c11 := rt1[11];
rt1_c12 := rt1[12];
rt1_c13 := rt1[13];
rt1_c14 := rt1[14];
rt1_c15 := rt1[15];
rt1_c16 := rt1[16];
rt1_c17 := rt1[17];
rt1_c18 := rt1[18];
rt1_c19 := rt1[19];
rt2_c0 := rt2[0];
rt2_c1 := rt2[1];
rt2_c2 := rt2[2];
rt2_c3 := rt2[3];
rt2_c4 := rt2[4];
rt2_c5 := rt2[5];
rt2_c6 := rt2[6];
rt2_c7 := rt2[7];
rt2_c8 := rt2[8];
rt2_c9 := rt2[9];
rt2_c10 := rt2[10];
rt2_c11 := rt2[11];
rt2_c12 := rt2[12];
rt2_c13 := rt2[13];
rt2_c14 := rt2[14];
rt2_c15 := rt2[15];
rt2_c16 := rt2[16];
rt2_c17 := rt2[17];
rt2_c18 := rt2[18];
rt2_c19 := rt2[19];
rt3_c0 := rt3[0];
rt3_c1 := rt3[1];
rt3_c2 := rt3[2];
rt3_c3 := rt3[3];
rt3_c4 := rt3[4];
rt3_c5 := rt3[5];
rt3_c6 := rt3[6];
rt3_c7 := rt3[7];
rt3_c8 := rt3[8];
rt3_c9 := rt3[9];
rt3_c10 := rt3[10];
rt3_c11 := rt3[11];
rt3_c12 := rt3[12];
rt3_c13 := rt3[13];
rt3_c14 := rt3[14];
rt3_c15 := rt3[15];
rt3_c16 := rt3[16];
rt3_c17 := rt3[17];
rt3_c18 := rt3[18];
rt3_c19 := rt3[19];
ob1_c0 := ob1[0];
ob1_c1 := ob1[1];
ob1_c2 := ob1[2];
ob1_c3 := ob1[3];
ob1_c4 := ob1[4];
ob1_c5 := ob1[5];
ob1_c6 := ob1[6];
ob1_c7 := ob1[7];
ob1_c8 := ob1[8];
ob1_c9 := ob1[9];
ob1_c10 := ob1[10];
ob1_c11 := ob1[11];
ob1_c12 := ob1[12];
ob1_c13 := ob1[13];
ob1_c14 := ob1[14];
ob1_c15 := ob1[15];
ob1_c16 := ob1[16];
ob1_c17 := ob1[17];
ob1_c18 := ob1[18];
ob1_c19 := ob1[19];
ob2_c0 := ob2[0];
ob2_c1 := ob2[1];
ob2_c2 := ob2[2];
ob2_c3 := ob2[3];
ob2_c4 := ob2[4];
ob2_c5 := ob2[5];
ob2_c6 := ob2[6];
ob2_c7 := ob2[7];
ob2_c8 := ob2[8];
ob2_c9 := ob2[9];
ob2_c10 := ob2[10];
ob2_c11 := ob2[11];
ob2_c12 := ob2[12];
ob2_c13 := ob2[13];
ob2_c14 := ob2[14];
ob2_c15 := ob2[15];
ob2_c16 := ob2[16];
ob2_c17 := ob2[17];
ob2_c18 := ob2[18];
ob2_c19 := ob2[19];
ob3_c0 := ob3[0];
ob3_c1 := ob3[1];
ob3_c2 := ob3[2];
ob3_c3 := ob3[3];
ob3_c4 := ob3[4];
ob3_c5 := ob3[5];
ob3_c6 := ob3[6];
ob3_c7 := ob3[7];
ob3_c8 := ob3[8];
ob3_c9 := ob3[9];
ob3_c10 := ob3[10];
ob3_c11 := ob3[11];
ob3_c12 := ob3[12];
ob3_c13 := ob3[13];
ob3_c14 := ob3[14];
ob3_c15 := ob3[15];
ob3_c16 := ob3[16];
ob3_c17 := ob3[17];
ob3_c18 := ob3[18];
ob3_c19 := ob3[19];
ort1_c0 := ort1[0];
ort1_c1 := ort1[1];
ort1_c2 := ort1[2];
ort1_c3 := ort1[3];
ort1_c4 := ort1[4];
ort1_c5 := ort1[5];
ort1_c6 := ort1[6];
ort1_c7 := ort1[7];
ort1_c8 := ort1[8];
ort1_c9 := ort1[9];
ort1_c10 := ort1[10];
ort1_c11 := ort1[11];
ort1_c12 := ort1[12];
ort1_c13 := ort1[13];
ort1_c14 := ort1[14];
ort1_c15 := ort1[15];
ort1_c16 := ort1[16];
ort1_c17 := ort1[17];
ort1_c18 := ort1[18];
ort1_c19 := ort1[19];
ort2_c0 := ort2[0];
ort2_c1 := ort2[1];
ort2_c2 := ort2[2];
ort2_c3 := ort2[3];
ort2_c4 := ort2[4];
ort2_c5 := ort2[5];
ort2_c6 := ort2[6];
ort2_c7 := ort2[7];
ort2_c8 := ort2[8];
ort2_c9 := ort2[9];
ort2_c10 := ort2[10];
ort2_c11 := ort2[11];
ort2_c12 := ort2[12];
ort2_c13 := ort2[13];
ort2_c14 := ort2[14];
ort2_c15 := ort2[15];
ort2_c16 := ort2[16];
ort2_c17 := ort2[17];
ort2_c18 := ort2[18];
ort2_c19 := ort2[19];
ort3_c0 := ort3[0];
ort3_c1 := ort3[1];
ort3_c2 := ort3[2];
ort3_c3 := ort3[3];
ort3_c4 := ort3[4];
ort3_c5 := ort3[5];
ort3_c6 := ort3[6];
ort3_c7 := ort3[7];
ort3_c8 := ort3[8];
ort3_c9 := ort3[9];
ort3_c10 := ort3[10];
ort3_c11 := ort3[11];
ort3_c12 := ort3[12];
ort3_c13 := ort3[13];
ort3_c14 := ort3[14];
ort3_c15 := ort3[15];
ort3_c16 := ort3[16];
ort3_c17 := ort3[17];
ort3_c18 := ort3[18];
ort3_c19 := ort3[19];

END_PROGRAM

CONFIGURATION Config0
  RESOURCE Res0 ON PLC
    TASK task0(INTERVAL := T#100ms, PRIORITY := 0);
    PROGRAM instance0 WITH task0 : sorter;
  END_RESOURCE
END_CONFIGURATION
